-- Schéma PostgreSQL — source de vérité unique : Alembic (`alembic/versions/`,
-- baseline `0001_baseline_schema.py`).
--
-- Ce fichier ne crée plus aucune table (E2-S2, Sprint 159) : le schéma est appliqué
-- par `alembic upgrade head` (entrypoint Docker en conteneur, manuellement en local).
-- Il reste monté dans `/docker-entrypoint-initdb.d/` uniquement pour rétrocompat du
-- volume postgres neuf, et n'est plus qu'un no-op.
--
-- Ne PAS rajouter de DDL ici : toute évolution de schéma passe par une nouvelle
-- révision Alembic chaînée après la baseline.
